name: riverpod_mutations_annotation
description: The annotation for riverpod_mutations_generator
version: 2.0.0-dev.0
repository: https://github.com/TekExplorer/riverpod_mutations_annotation

environment:
  sdk: ^3.6.0-0

dependencies:
  meta: ^1.0.0
  riverpod: ^3.0.0-dev.17
  collection: ^1.19.0
  riverpod_annotation: ^3.0.0-dev.17

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
