name: riverpod_mutations_annotation
description: The annotation for riverpod_mutations_generator
version: 1.0.2-dev.2
repository: https://github.com/TekExplorer/riverpod_mutations_annotation

environment:
  sdk: ^3.0.0

dependencies:
  meta: ^1.0.0
  riverpod: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
